version: "3"

services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes: 
      - .:/var/www/html
      - dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laraveldockerize

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: lcp_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - dockerize/mysql/data:/var/lib/mysql
      - dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - laraveldockerize


  app:
    build:
      context: .
      dockerfile: dockerize/app/php.dockerfile
    image: digitalocean.com/php
    container_name: lcp_app
    volumes: 
      - .:/var/www
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - laraveldockerize 


#Docker Networks
networks:
  laraveldockerize: